BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS [Roles] 
(
    [Id] VARCHAR(36) NOT NULL UNIQUE CONSTRAINT [PK_Roles] PRIMARY KEY,
    [Name] NVARCHAR(256) NOT NULL,
    [NormalizedName] NVARCHAR(256) NOT NULL CONSTRAINT [IX_Roles_NormalizedName] UNIQUE,
    [ConcurrencyStamp] NVARCHAR(4000) NOT NULL
);

COMMIT;