BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS [UserClaims] 
(
    [Id] INTEGER NOT NULL CONSTRAINT [PK_UserClaims] PRIMARY KEY AUTOINCREMENT,
    [ClaimType] VARCHAR(255) NOT NULL,
    [ClaimValue] VARCHAR(255),
    [UserId] VARCHAR(36) NOT NULL,
    CONSTRAINT FK_UserUserClaim FOREIGN KEY (UserId) REFERENCES Users(Id) ON UPDATE CASCADE ON DELETE CASCADE
);

COMMIT;